spring.application.name=royawl-api-gateway

# ====================== Eureka ======================
eureka.client.service-url.defaultZone=http://royawl-eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# ====================== Load Balancer ======================
spring.cloud.loadbalancer.enabled=true

# ====================== Gateway Routes ======================
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ====================== Forwarded Headers ======================
spring.cloud.gateway.forwarded.enabled=true
spring.cloud.gateway.x-forwarded.enabled=true

# Route for royawl-api
spring.cloud.gateway.routes[0].id=royawl-api
spring.cloud.gateway.routes[0].uri=lb://royawl-api
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**
spring.cloud.gateway.routes[0].filters[0]=PreserveHostHeader

# 2. WebSocket Route (wpi)
spring.cloud.gateway.routes[1].id=royawl-api-websocket
spring.cloud.gateway.routes[1].uri=lb://royawl-api
spring.cloud.gateway.routes[1].predicates[0]=Path=/wsi/**
spring.cloud.gateway.routes[1].filters[0]=PreserveHostHeader

# 3. Actuator / Metrics Route (optional - you can expose or hide)
spring.cloud.gateway.routes[2].id=royawl-api-actuator
spring.cloud.gateway.routes[2].uri=lb://royawl-api
spring.cloud.gateway.routes[2].predicates[0]=Path=/actuator/**
spring.cloud.gateway.routes[2].filters[0]=PreserveHostHeader

# Route for royawl-job
#spring.cloud.gateway.routes[3].id=royawl-job
#spring.cloud.gateway.routes[3].uri=lb://royawl-job
#spring.cloud.gateway.routes[3].predicates[0]=Path=/job/**
#spring.cloud.gateway.routes[3].filters[0]=PreserveHostHeader

# Route for royawl-recommendation-service
#spring.cloud.gateway.routes[4].id=royawl-recommendation-service
#spring.cloud.gateway.routes[4].uri=lb://royawl-recommendation-service
#spring.cloud.gateway.routes[4].predicates[0]=Path=/recommendations/**
#spring.cloud.gateway.routes[4].filters[0]=PreserveHostHeader


# ====================== Actuator ======================
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always

server.ssl.enabled=true
server.port=443
server.ssl.key-store=classpath:server-ssl.p12
server.ssl.key-store-password=ENC(9X939yRQzXFepOmptu7kErMUOrveWr+sbVsv6w43fE4i71LJkL/1DBNnPQWU8g9i)
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=apiroyawl


app.exposed-headers=Authorization,hasMore,currentChunkIndex,totalChunks
app.allowed-origins=https://www.royawl.com,https://royawl.com
